/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.t45k.pct

import io.github.t45k.pct.coroutine.FileIOTrial

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main() {
    val start = System.currentTimeMillis()
    FileIOTrial.coroutine()
    println(System.currentTimeMillis() - start)
}
