/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.t45k.pct

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main() {
    io.github.t45k.pct.coroutine.doc.main()
}
