/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.t45k.pct

import io.github.t45k.pct.coroutine.Main

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main() {
    Main().main()
}
